Update README.md with a more informative example of suppressing logs in test environments.
As a braintree newb I lost some time yesterday setting up my test environment
by following your README example for suppressing logs, however it caused this
error:

undefined method `logger=' for #<Braintree::Configuration:0x0056144b673760>